/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '09/11/16 13:58' with Gradle 3.1
 *
 * @author luisb, @date 09/11/16 13:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
